name: Handle Issues

on: issues

jobs:
  output-info:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details
        run: |
          echo "Action: ${{ github.event.action }}"
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue Body: ${{ github.event.issue.body }}"

          created_at="${{ github.event.issue.created_at }}"
          formatted_date=$(date -d "$created_at" +"%m/%d/%Y %I:%M %p %Z")

          echo "Issue Created at: $formatted_date"
          echo "Issue URL: ${{ github.event.issue.html_url }}"
